name: smart_switch_team13
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.18.0
  lottie: ^3.1.0
  shared_preferences: ^2.0.0
  email_validator: ^2.0.1
  url_launcher: ^6.0.19
  flutter_email_sender: ^6.0.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  sqflite: ^2.0.0+4
  path: ^1.8.0
  mqtt_client: ^10.2.1
  image_picker: ^1.1.0
  flutter_animate: ^4.5.0
  speech_to_text: ^6.6.1
  uuid: ^4.4.0
  flutter_rating_bar: ^4.0.1
  mailer: ^6.1.0
  provider: ^6.1.2
  awesome_notifications: ^0.9.3+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logonew.png"

flutter:
  uses-material-design: true

  assets:
    - images/background.png
    - images/background2.png
    - images/background3.png
    - images/logo.png
    - images/back.png
    - images/Vector.png
    - images/Preferences-bro 1.svg
    - images/user_male.png
    - images/eye.png
    - images/eye_hide.png
    - Fonts/
    - icon/lampe.ico
    - icon/lampeOn.ico
    - icon/Microphone.ico
    - icon/tvOn.ico
    - icon/tvOff.ico
    - icon/home.ico
    - icon/homeOn.ico
    - icon/sCENCE_1.ico
    - icon/scenceON.ico
    - icon/add.ico
    - icon/Setting.ico
    - icon/paramettre.ico
    - icon/controle.ico
    - icon/controleOn.ico
    - icon/addition.ico
    - images/Loading.png
    - animation/loadin.json
    - images/search.png
    - images/Basemap.png
    - images/localisation.png
    - images/review-bro.png
    - images/Online world-bro 1.png
    - images/Bluetooth.png
    - images/simple-icons_esphome.png
    - images/Smart_home_bro1.png
    - images/Questions_bro.png
    - images/Wifi.png
    - icon/notifcations.ico
    - images/backyellow.png
    - images/char.png
    - images/iphone11.png
    - images/iphone12.png
    - images/Mobile.png
    - images/Startled.png
    - images/woman.png
    - images/yellow_first.png
    - images/yellow3.png
    - images/checked.png
    - images/notchecked.png
    - images/Feedback-bro 1.png
    - images/Star1.png
    - images/Star 2.png
    - images/Contact us-bro 1.png
    - images/vide.png
    - images/Reminders-bro.png
    - images/logonew.png
    - images/discord.png
    - images/facebook.png
    - images/gmail.png
    - images/instagram.png
    - images/Animation - 1714769953036.json
    - images/cloud.json
    - images/loadImage.json
    - images/rain.json
    - images/sun.json
    - images/sunCloud.json
    - images/tv2.png
    - images/tv (1).png
    - images/vector_246_x2.png
    - images/s-l640 1.png
    - images/Frame 3713.png
    - images/Frame 20.png
    - images/lighon.png
    - images/light.png
